import React from 'react';
import FriendsHeader from './header';
import FriendList from './friend-list';
import { Metadata } from 'next';


export const metadata: Metadata = {
  title: "Hudddle | Friends",
  //description: "Generated by create next app",
};
interface FriendsPageProps {
  tab: string;
  page: number;
}

const FriendsPage: React.FC<FriendsPageProps> = ({ tab, page }) => {
  return (
    <div className='pt-8 pb-10 px-12'>
      <FriendsHeader searchPage={false} />
      <FriendList tab={tab} page={page} />
    </div>
  );
};

export default FriendsPage;
