import React from 'react'
import FriendsHeader from '../header'
import { Card } from '@/components/ui/card'
import InviteFriends from './invite-friends';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Hudddle | Search Friends",
  //description: "Generated by create next app",
};
interface SearchProps {
  search: string,
}
const SearchFriendsPage: React.FC<SearchProps> = ({ search }) => {
  const title = "Search for your friend on Hudddle";
  return (
    <div className='pt-8 pb-10 px-12'>
      <FriendsHeader searchPage={true} />
      <Card className='pt-10 pb-20 flex justify-center border-none neo-effect mb-10 mt-20'>
        <InviteFriends title={title} initialValue={search} />
      </Card>
    </div>
  )
}

export default SearchFriendsPage