
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@fontsource/red-hat-text";
import "@fontsource/red-hat-text/400.css";
import "@fontsource/red-hat-text/400-italic.css"; 
import StoreProvider from "@/store/StoreProvider";
import { Toaster } from "@/components/ui/toaster"
// import { AuthContext } from "@/contexts/AuthContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          {children}
          <Toaster />
          </body>
      </html>
    </StoreProvider>
  );
}
